# Default values for web-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

events:
  enabled: false
  image:
    repository: "thanhpx/web-base:latest"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 
    imagePullSecrets:
  targetPort:
  portName:

  podLabels: {} 
  annotations: {}
  
  resources: {}


# landingpage
landingpage:
  enabled: false
  annotations:
  podLabels:
  image:
    repository: "thanhpx/web-base:latest"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 

    imagePullSecrets:
  targetPort:
  portName:
  resources: {}


service:
  enabled: false
  annotations:

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}
  tls: {}
    # - hosts:
    #   - <host_name>
    #   secretName: <ssl_cert_secret> 
  hosts: {}
    # <host_name>:
    #   paths:
    #   - <path>:
    #     pathType: <type>        > Prefix, Exact, Mixed
    #     path: "<path>"
    #     backendService: <service_name>
    #     targetPort: <service_port>      > equivalent port of service, allow number or string(port_name)

nodeSelector: {}

tolerations: []

affinity: {}
