{{ if .Values.events.enabled }}
apiVersion: apps/v1
kind: Deployment
{{- $name := print (include "web-base.fullname" .) "-events" }}
metadata:
  name: {{ $name  }}
  namespace: {{ include "web-base.namespace" . }}
  labels: 
    {{- include "web-base.labels" . | nindent 4 }}
  {{ with .Values.events.annotations }}
  annotations: 
      {{- toYaml . | nindent 4 -}}
  {{- end }} 
spec:
  selector:
    matchLabels:
      {{- include "web-base.selectorLabels" . | nindent 6  }}
  template:
    metadata:
      labels:
      {{- include "web-base.selectorLabels" . | nindent 8 }}
      {{- with .Values.events.podLabels -}}
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      {{ with .Values.events.annotations -}}
      annotations: 
      {{- toYaml . | nindent 4 -}}
      {{- end }} 
    # {{ .Values.events.image.imagePullSecret }} {{ .Values.events.image.pullPolicy }}
    spec:
      {{- with .Values.events.image.imagePullSecrets }}
      imagePullSecrets:  
        {{- toYaml . | nindent 8 -}}
      {{ end }}
      containers:
      - name: {{ $name }}
        image: {{ include "utils.get-image" .Values.events  }}
        imagePullPolicy:  {{ .Values.events.image.pullPolicy }}
        resources:
          {{- include "utils.get-resources" .Values.events | nindent 10 }}
        ports:
        - containerPort: !!int {{ default 80 .Values.events.targetPort }}
          {{- with .Values.events.portName -}}
          name: {{ . }}
          {{ end }}
{{ end }}