{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-base.fullname" . }}
  namespace: {{ include "web-base.namespace" . }}
  labels:
      {{- include "web-base.labels" . | nindent 4 }}
  {{ with .Values.service.annotations }}
  annotations: 
      {{- toYaml . | nindent 4 -}}
  {{- end }}
spec:
  selector:
  {{- include "web-base.selectorLabels" . | nindent 4 }}
  ports:
  {{- if .Values.landingpage.enabled }}
  - name: "landingpage"
    port: 3000
    targetPort: {{ .Values.landingpage.targetPort }}
  {{- end -}}
  {{- if .Values.events.enabled }}
  - name: "events"
    port: 80
    targetPort: {{ .Values.events.targetPort }}
  {{ end -}}
{{- end -}}