{{- if .Values.admin.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ print (include "biploma.fullname" .) "-admin"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: mongo
    {{- include "biploma.labels" . | nindent 4 }}
  {{- with .Values.admin.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4  }}
  {{- end }}
spec:
  type: {{ .Values.admin.service.type  }}
  {{- if and ( eq .Values.admin.service.type "ClusterIP" ) .Values.admin.service.clusterIP }}
  clusterIP: {{ .Values.admin.service.clusterIP }}
  {{- end }}
  {{- if and ( eq .Values.admin.service.type "LoadBalancer" ) .Values.admin.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.admin.service.loadBalancerIP }}
  {{- end }}
  {{- if  .Values.admin.service.externalIPs }}
  externalIPs: {{ toYaml .Values.admin.service.externalIPs | nindent 4 }}
  {{- end }}
  ports:
  - name: {{ .Values.admin.service.portName }}
    port: {{ .Values.admin.service.port }}
    targetPort: admin
    {{- if and ( or ( eq .Values.admin.service.type "LoadBalancer" ) ( eq .Values.admin.service.type "NodePort" )) .Values.admin.service.nodePort }}
    nodePort: {{ .Values.admin.service.nodePort  }}
    {{- else if eq .Values.admin.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  selector:
    name: {{ print  (include "biploma.fullname" .) "-admin" }}
    app:  {{ include "biploma.fullname" . }}

{{- end }}
